Controllers/csat_settings_pageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using OwnYITCSAT.DataAccessLayer;
using System.IO;
using OwnYITCSAT.Models;
using System.Text;
using Newtonsoft.Json;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Http;

namespace OwnYITCSAT.Controllers
{
    public class csat_settings_pageController : Controller
    {
        DBQueryHandler Objquery = new DBQueryHandler();
        OwnYITCommon objcommon = new OwnYITCommon();
        DataTable dtsubtosubmenu = new DataTable();
        //  Jsondata abc = new Jsondata();        
        DataTable dt = new DataTable();
        DataTable dt1 = new DataTable();
        int querystatus = 0;
        string result = "";
        int cnt = 0;
        string strquery;
        string searchdata = "";
        string hdnram;
        string hdnhdd;
        string hdncd;
        string hdnlan;
        string hdnwifi;
        string hdnav;
        public IActionResult csat_settings_page(int id)
        {
            //session time out start
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.password = HttpContext.Session.GetString("password");
            if (ViewBag.username == null && ViewBag.password == null)
            {
                return RedirectToAction("session_time_out", "csat_login");
            }
            else if (ViewBag.username == "" && ViewBag.password == "")
            {
                return RedirectToAction("csat_login", "csat_login");
            }
            else
                //session time out end
                try
                {
                    TempData["notselect"] = "";
                    if (OwnYITConstant.DT_SETTINGS_MENU == null)
                    {
                        OwnYITConstant.DT_SETTINGS_MENU = Objquery.Get_SubMenu(id);
                    }
                    if (id.ToString() == null)
                        return RedirectToAction("csat_login", "csat_login");
                    if (OwnYITConstant.DT_SETTINGS_MENU == null)
                        return RedirectToAction("csat_login", "csat_login");
                }
                catch (Exception ex)
                {
                    objcommon.WriteLog("csatsettingController", "csat_settings_page Exception : " + ex.Message.ToString());
                }
            return View();
        }

        public ActionResult get_Submenu(int catid)
        {
            //session time out start
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.password = HttpContext.Session.GetString("password");
            if (ViewBag.username == null && ViewBag.password == null)
            {
                return RedirectToAction("session_time_out", "csat_login");
            }
            else if (ViewBag.username == "" && ViewBag.password == "")
            {
                return RedirectToAction("csat_login", "csat_login");
            }
            else
                //session time out end
                try
                {
                    dtsubtosubmenu = Objquery.Get_SubMenu(catid);
                    DataColumn dcolColumn = new DataColumn("class", typeof(string));
                    dtsubtosubmenu.Columns.Add(dcolColumn);
                    OwnYITConstant.DT_SETTINGS_SUB_MENU = GetCssData(dtsubtosubmenu);
                }
                catch (Exception ex)
                {
                    objcommon.WriteLog("csatsettingController", "get_Submenu Exception : " + ex.Message.ToString());
                }
            return View("csatsetting");

        }
        public DataTable GetCssData(DataTable dtcss)
        {
            try
            {
                for (int i = 0; i < dtcss.Rows.Count; i++)
                {

                    if ("Scann IP Range" == dtcss.Rows[i]["menu_name"].ToString())//Agent Management Menu start
                        dtcss.Rows[i]["class"] = "scan-ip-range";
                    else if ("Agent Installation" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "agent-installation";
                    else if ("Agent Installation Status" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "agent-installatin-status";
                    else if ("Agent Uninstall" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "agent-uninstall";
                    else if ("Authorize IP Range" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "authorize-ip-range";
                    else if ("Agent Release License" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "agent-realease-license";
                    else if ("Branch/Unit Level Creation" == dtcss.Rows[i]["menu_name"].ToString())//Organization Structure Management Menu start
                        dtcss.Rows[i]["class"] = "branch-level-creation-1";
                    else if ("Manage Branch/Unit" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "change-user-password";
                    else if ("Unlink Agent From Branch/Unit" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "admin-access-rights";
                    else if ("Branch/Unit IP Range Binding" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "unlink-agent";
                    else if ("Manage Admin User" == dtcss.Rows[i]["menu_name"].ToString())//Admin User Management Menu start
                        dtcss.Rows[i]["class"] = "manage-admin-user";
                    else if ("Change User Password" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "change-user-password";
                    else if ("Admin User Access Rights" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "admin-access-rights";
                    else if ("Agent Configuration" == dtcss.Rows[i]["menu_name"].ToString())//Configuration Management Menu start
                        dtcss.Rows[i]["class"] = "agent-configuration";
                    else if ("Authorize IP for Accessing GUI" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "authorize-ip-for-accessing-gui";
                    else if ("Manage Process Category" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "manage-process-category";
                    else if ("Database Maintanance" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "database-maintanance";
                    else if ("Manage Disk Clean Up" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "manage-disk-cleanup";
                    else if ("Setting For Mail Report" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "setting-for-mail-report";
                    else if ("Remote File Execution" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "remote-file-execute";
                    else if ("Event Viewer Monitoring" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "remote-file-execute";
                    else if ("Agent Patch Management" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "agent-patch-management";
                    else if ("Service Setting" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "service-setting";
                    else if ("Configuration Setting" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "configuration-settings";
                    else if ("SSH Configuration" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "configuration-settings";
                    else if ("Create Notification" == dtcss.Rows[i]["menu_name"].ToString())//Alert Notification Handling
                        dtcss.Rows[i]["class"] = "create-notification-1";
                    else if ("Desired Configuration Management" == dtcss.Rows[i]["menu_name"].ToString())//Compliance Management
                        dtcss.Rows[i]["class"] = "desired-configuration-mgmt";
                    else if ("Exclusion IP for Compliance" == dtcss.Rows[i]["menu_name"].ToString())
                        dtcss.Rows[i]["class"] = "exclution-ip-for-compliance";

                }
            }
            catch (Exception ex)
            {

                objcommon.WriteLog("csatsettingController", "GetCssData Exception : " + ex.Message.ToString());
            }
            return dtcss;
        }
        public IActionResult setting_flag_onoff()
        {
            //session time out start
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.password = HttpContext.Session.GetString("password");
            if (ViewBag.username == null && ViewBag.password == null)
            {
                return RedirectToAction("session_time_out", "csat_login");
            }
            else if (ViewBag.username == "" && ViewBag.password == "")
            {
                return RedirectToAction("csat_login", "csat_login");
            }
            else
                return View();
        }
        public IActionResult authorizeip_access_gui()
        {
            //session time out start
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.password = HttpContext.Session.GetString("password");
            if (ViewBag.username == null && ViewBag.password == null)
            {

Views/csat_settings_page/admin_menu.cshtml
@*@using OwnYITCSAT.DataAccessLayer;*@

<div class="category-tree mb30">
    <ul class="subcategories">
        <li class="130 form_label div_none @(ViewContext.RouteData.Values["Action"].ToString() == "setting_organization_structure" ? "active" : "")">@Html.ActionLink("Organization Structure", "setting_organization_structure", "csat_settings_page")</li>
        <li class="134 div_none @(ViewContext.RouteData.Values["Action"].ToString() == "setting_user_mgmt" ? "active" : "")">@Html.ActionLink("User Management", "setting_user_mgmt", "csat_settings_page")</li>
    </ul>
</div>
<script>
    $(function () {
        var current_page_URL = location.href;
        $("a").each(function () {
            if ($(this).attr("href") !== "#") {
                var target_URL = $(this).prop("href");
                if (target_URL == current_page_URL) {
                    $('.category-tree').parents('li, ul').removeClass('active');
                    $(this).parent('li').addClass('active');
                    return false;
                }
            }
        });
    });
</script>

Views/csat_settings_page/authorizeip_access_gui.cshtml
@{
    ViewData["Title"] = "authorizeip_access_gui";
    Layout = "~/Views/Shared/ownyit_main_page.cshtml";
}
<script src="~/js/ipaddress_validation.js"></script>
<body onload="showauthipaddress();">
    <div class="row">

        <div class="ibox float-e-margins ">
            <div class="ibox-content" style="padding:4px;">               
                <ul class="breadcrumb" style="margin-bottom:0px;">
                    <li>
                        @Html.ActionLink("Settings", "setting_scan_ip_range", "csat_settings_page")
                        <i class="icon-angle-right"></i>
                    </li>
                    <li>Authorized IP Access GUI</li>
                </ul>
            </div>
        </div>

        <!--side menu-->
        <div class="col-sm-2 col-md-2 col-lg-2 no_padding">
            <div class="ibox float-e-margins ">
                <div class="ibox-content sidemenu">
                    @{
                        @Html.Partial("csat_settings_page_menu");
                    }
                </div>
            </div>
        </div>
        <!--side menu end-->

        <div class="col-sm-10 col-md-10 col-lg-10">
            <div class="ibox float-e-margins" style="margin-bottom: 10px;">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-xs-12">
                            <form class="form-horizontal" method="post" name="ip_scan_form">
                                <div class="form-group">
                                    <label for="nameField" class="col-xs-1">IP Address</label>
                                    <div class="col-xs-2">
                                        <input type="text" name="accessip" id="accessip" class="form-control ip_address" placeholder="Enter IP" />
                                    </div>
                                    <div class="pull-left col-xs-1">
                                        <input type="button" class="btn btn-primary" value="Add IP" id="btnsavescanip" onclick="authip_accessGUI()">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <!--form  content end-->

            <div class="row ibox2">
                <div class="col-sm-12 col-md-12 col-lg-12 ibox2-content" id="divauthip_div">
                    <table id="divauthip" class="table table-striped table-bordered " width="100%"></table>
                </div>
            </div>
        </div>
        <div class="space_bottom">&nbsp;</div>
    </div>
    <!--delete_range device model  content-->
    <div class='modal fade ' id='delete_range' tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
        <div class='modal-dialog  modal-small'>
            <div class='modal-content '>
                <div class='modal-header'>
                    <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
                    <h6 class='modal-title'>Conformation </h6>
                </div>
                <div class='modal-body'>
                    <!--form  content-->
                    <div class='row'>
                        <div class='col-sm-12 col-md-12 col-lg-12'>

                            <div class='row'>
                                <div class='col-xs-12'>
                                    <form class='form-horizontal' method='post'>
                                        <div class='form-group'>

                                            <label for='nameField' class='col-xs-12'>
                                                <i class='glyphicon glyphicon-exclamation-sign delete_msg'></i>
                                                <span style='font-weight:normal;margin-left:30px;'>Are you sure you want to delete this record?</span>
                                            </label>

                                        </div>
                                        <div class='form-group'>
                                            <label for='nameField' class='col-xs-4'></label>
                                            <div class='col-xs-6'>
                                                <input type='button' class='btn btn-primary' name='yes' value='Yes' id="btnauthguidelete" />
                                                <input type='button' class='btn btn-default' data-dismiss="modal" name='no' value='No' />
                                            </div>
                                        </div>
                                    </form>
                                </div>

                            </div>

                        </div>
                    </div>  <!--form  content end-->
                </div>

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- delete_range main node popup model box  Content-->
    @*// Scan IP range*@
    <script>
        function showauthipaddress() {
            $("#overlay").show();
            $("#overlay").fadeIn(300);
        $.ajax({
            type: "POST",
            url: '@Url.Content("~/csat_settings_page/GetAuthIPAddress")',
            success: function (data) {
                //debugger;
                var dataclear = document.getElementById('divauthip_div');
                dataclear.innerHTML = '&nbsp;';
                $('#divauthip_div').append("<table id='divauthip' class='table table-striped table-bordered' width='100%'></table>");
                dtable = document.getElementById('divauthip');
                var data1 = [];
                for (var i = 0; i < data.dtauthip.length; i++) {
                    //debugger;
                    var delete_div = "<i class=' glyphicon glyphicon-trash manage_icon ' type='button' data-toggle='modal'  title='Delete' onclick=deleteauthipgui('" + data.dtauthip[i].ipaddress + "')></i>";
                    data1.push([data.dtauthip[i].ipaddress, delete_div]);
                }
                var dtable = $("#divauthip").DataTable({
                    data: data1, scrollX: !0, searching: !1, dom: "<'top'lB>rt<'bottom'ip><'clear'>", buttons: ["colvis"],
                    columns: [{ title: "IP Address" },{ title: "Delete", orderable: false,className: 'dt-center', width: '30px' }]
                });
                $(".table").css({ "width": "100%" });
                $(".dataTables_scrollHeadInner ").css({ "width": "100%" });
            }

        }).done(function () {
            setTimeout(function () {
                $("#overlay").fadeOut(300);
            }, 500);
        });
    }

        function authip_accessGUI() {          
           // debugger;
                 var varipadd = document.getElementById('accessip').value;
                 var ip = varipadd.split(".");
                    if (ip.length != 4) {
                        alert("Please provide Proper IP Range !");                       
                        return false;
                    }
                    //Check Numbers
                    for (var c = 0; c < 4; c++) {
                        //Perform Test
                        if (!(1 / ip[c] > 0) || ip[c] > 255 || isNaN(parseFloat(ip[c])) || !isFinite(ip[c]) || ip[c].indexOf(" ") !== -1) {
                            alert("Please provide Proper IP Range !");
                            return false;
                        }
                    }  
                     //alert("Please provide Proper IP Range !");
                     $.ajax({
                        type: "POST",
                         url: '@Url.Content("~/csat_settings_page/AddAuthIPAddress?ipaddress=")' + varipadd,
                         success: function (data) {
                          // debugger;
                            alert(data);                          
                             showauthipaddress();
                             document.getElementById('accessip').value = "";
                        }
                     });
          }

    // Delete Scan IP Range
        var ipaddress2 = "";  
        function deleteauthipgui(ipaddress) {
      //  debugger;       
            ipaddress2 = ipaddress
           $('#delete_range').modal('show');
        }
        $('#btnauthguidelete').on('click',function(){
            var url1 = '@Url.Content("~/csat_settings_page/DeleteAuthGUIIP?ipaddress=")' + ipaddress2;
        $.ajax({
        type: "POST",
        url: url1,
        success: function (result) {
            alert(result);
            $('#delete_range').modal('hide');
            showauthipaddress();
            ipaddress = "";            
		 }
		 });

	});


    </script>
    <script>
        $('.ip_address').mask('099.099.099.099');
    </script>
</body>

Views/csat_settings_page/setting_configuration.cshtml
@{
    ViewData["Title"] = "setting_configuration";
    Layout = "~/Views/Shared/ownyit_main_page.cshtml";
}


<div class="row">
   

        <div class="ibox float-e-margins ">
            <div class="ibox-content" style="padding:4px;">
                <div class="pull-right form_label btn_top_margin">
                    <button type="button" class="btn btn-primary btn-md day" onclick='AddConfiguration()'> Apply Configuration </button>
                </div>
                <ul class="breadcrumb" style="margin-bottom:0px;">
                    <li>
                        @Html.ActionLink("Settings", "setting_scan_ip_range", "csat_settings_page")
                        <i class="icon-angle-right"></i>
                    </li>
                    <li> Configuration Setting </li>
                </ul>
            </div>
        </div>
    
        <div class="col-sm-2 col-md-2 col-lg-2 no_padding">
            <div class="ibox float-e-margins ">
                <div class="ibox-content sidemenu">
                    @{
                        @Html.Partial("csat_settings_page_menu");
                    }
                </div>
            </div>
        </div>
        <!--side menu end-->

        <div class="col-sm-10 col-md-10 col-lg-10">
            <div class="ibox float-e-margins" style="margin-bottom: 10px;">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-12">

                            <div class="row">
                                <div class="col-xs-12">
                                    <form class="form-horizontal" method="post">
                                        <div class="form-group">
                                            <label for="nameField" style="margin-top: -5px;background-color: #fff;text-align: center;color: #3D93C8;width: 170px;" class="col-xs-2 form_label">&nbsp;&nbsp;Advance Configuration&nbsp;&nbsp;</label>
                                            <div class="col-xs-10">
                                            </div>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-12">
                            @*<button type="button" class="btn btn-primary pull-right " style="margin-bottom: 5px;" onclick='AddConfiguration()'> Apply Configuration </button>*@
                            <div class="form-group">
                                <label for="nameField" class="col-xs-1">Section: </label>
                                <div class="col-xs-3">
                                    <select class="form-control col-sm-2 col-lg-2 col-md-2" name="Section Name " id="drpsection" onchange="GetConfiguration(this.value)"></select>
                                </div>
                            </div>
                            <div class="space_bottom">&nbsp;</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row ibox2">
                <div class="col-sm-12 col-md-12 col-lg-12 ibox2-content">
                    <div class="table-responsive" id="divconf">

                    </div>
                    <div class="space_bottom">&nbsp;</div>
                </div>
            </div>

            <div class="space_bottom">&nbsp;</div>
        </div>
 </div>

    @*<input type="submit" class="btn btn-primary pull-right" value="Add Configuration" onclick='AddConfiguration()' />*@
    @*<div class="form-group">
            <label for="nameField" class="col-xs-1">Section: </label>
            <div class="col-xs-2">
                <select class="form-control col-sm-1 col-lg-1 col-md-1" name="Section Name " id="drpsection" onchange="GetConfiguration(this.value)"></select>
            </div>
        </div>*@
    @*<div class="table-responsive" id="divconf">
        </div>*@


<script>
    $.get(null, null, databind);
    function databind() {
        $("#overlay").show();
        $("#overlay").fadeIn(300);
        var Sethrddata = $('#drpsection');
        jQuery('#drpsection').html('');
        $.ajax({
            type: "POST",
            url: '@Url.Content("~/csat_settings_page/GetConfigurationdata?sectionname=")' + "",
            success: function (data) {
                var sectiondata = "<option value='-1'>Select Section</option>";
                for (var i = 0; i < data.sectionname.length; i++) {
                    sectiondata += "<option value='" + data.sectionname[i].sectionname + "'>" + data.sectionname[i].sectiondisplayname + "</option>";
                }
                Sethrddata.append(sectiondata);
            }
        }).done(function () {
            setTimeout(function () {
                $("#overlay").fadeOut(300);
            }, 500);
        });
    }
    function GetConfiguration(sec) {
        $("#overlay").show();
        $("#overlay").fadeIn(300);
        var yes;
        var no;
      //  var sec = document.getElementById("drpsection").value;
        //  debugger;
            $.ajax({
            type: "POST",
            url: '@Url.Content("~/csat_settings_page/GetConfigurationdata?sectionname=")' + sec,
            success: function (data) {
          //  debugger;
                var setgriddata = $('#divconf');
                $('#divconf').html('');
                var headdata = "<table class='table table-striped table-bordered tblpaging' id='admin_user_datatable' style='width:100%'><thead><tr><th class='col-sm-2'>Property Name</th>" +
                    "<th class='col-sm-2' data-orderable='false'>Property Value</th></tr></thead><tbody>";
                var trdata = "";
                for (var i = 0; i < data.configdata.length; i++) {
                  //  trdata += "<tr class='abc'><td class='col-sm-2'>" + data.configdata[i].sectionname + "</td>";
                    trdata += "<tr><td class='col-sm-1'>" + data.configdata[i].propertyname + "</td>";
                    if (data.configdata[i].propertytype == "1") {
                        if (data.configdata[i].propertyvalue == "1")
                            yes = 'checked';
                        else
                            no = 'checked';
                        trdata += "<td class='col-sm-2'><input type='radio' id='yes'   name='" + data.configdata[i].propertyname + "' value='1' "+yes+" /> &nbsp;" + data.configdata[i].propertyvalue1;
                        trdata += "&nbsp;<input type='radio' id='no'  name='" + data.configdata[i].propertyname + "' value='0' "+no+"  />&nbsp;" + data.configdata[i].propertyvalue2 + "</td></tr> ";

                    }
                    else if (data.configdata[i].propertytype == "2")
                    {
                        trdata += "<td class='col-sm-2'><input type='checkbox' class='group4' name='check[]' id='gridrawcheck4' onchange='UncheckMain()' value='1' " + data.configdata[i].chk + " />" + data.configdata[i].propertyname + "</td></tr>";
                    }
                    else if (data.configdata[i].propertytype == "3") {
                        if (data.configdata[i].propertyname == "Database_Name")
                            trdata += "<td class='col-sm-2'><select class='form-control col-sm-3 col-lg-3 col-md-3' id='drpdbtype'><option value='0'>SQL Server</option><option value='3'>MYSQL</option></select></td>";
                        else if (data.configdata[i].propertyname == "DBConnection")
                            trdata += "<td class='col-sm-2'><select class='form-control col-sm-3 col-lg-3 col-md-3'id='drpdbconn'><option value='0'>SQL Connection</option><option value='1'>Windows DNS connection</option><option value='2'>Direct DNS connection</option></select></td>";
                        else if (data.configdata[i].propertyname == "CONNECTION_TIMEOUT")
                            trdata += "<td class='col-sm-2'><select class='form-control col-sm-3 col-lg-3 col-md-3' id='drpdbconntimeout'><option value='00'>00</option><option value='05'>05</option><option value='10'>10</option><option value='15'>15</option><option value='20'>20</option><option value='25'>25</option><option value='30'>30</option><option value='35'>35</option><option value='40'>40</option><option value='45'>45</option><option value='50'>50</option><option value='55'>55</option><option value='60'>60</option></select></td>";
                    }
                    else {
                            trdata += "<td class='col-sm-2'><div class='col-xs-5'><input type='text' class='form-control'  value='" + data.configdata[i].propertyvalue + "' /></div></td></tr>";
                    }
                    yes = "";
                    no = "";
                }
                setgriddata.append(headdata + trdata + "</tbody></table>");
                datatable_paging();

            }
            }).done(function () {
                setTimeout(function () {
                    $("#overlay").fadeOut(300);
                }, 500);
            });

    }
    var chkdata = "";
    function UncheckMain() {
       // debugger;
        chkdata = "";
        var checkboxes = document.querySelectorAll('input[id="gridrawcheck4"]');
        for (var i = 0; i < checkboxes.length; i++) {
            if (checkboxes[i].checked == true) {
                chkdata += ",1";
            }
            else {
                chkdata += ",0";
            }

        }
        //alert(crc);
    }
    function AddConfiguration() {
        //debugger;
        if ($("#drpsection").val() == "-1") {
            alert("Please select any one section !");
            return false;
        }
        else {
            var pro = "";
            var proval = "";
            var flag = true;
            var sec = document.getElementById("drpsection").value;

            $('#admin_user_datatable tbody tr').each(function () {
            //debugger;
                var value = $(this).find("td:eq(1) input[type='text']").val();
                if (typeof value == "undefined")
                    value = $(this).find("td:eq(1) input[type='radio']:checked").val();
                if (typeof value == "undefined")
                    value = $(this).find("select").val();
                if (typeof value == "undefined") {
                    if (flag == true) {
                        value = chkdata.substring(1);
                        flag = false;
                    }
                }
                if (value != "") {
                    var prop = $(this).find("td").eq(0).html();
                    pro += "," + prop;
                    proval += "!" + value;
                }
            });
            //if (proval.search('undefined'))
            //if (proval.indexOf('undefined') != '-1')
            //{
            //    proval.replace(/undefined/g, "");
            //    proval += chkdata;
            //}

            //debugger;
            $.ajax({
                type: "POST",
                url: '@Url.Content("~/csat_settings_page/AddConfiguration?sec=")' + sec + '&prop=' + pro + '&propval=' + proval,
                success: function (data) {
                    alert(data);
                }
            });
        }
    }

</script>