Controllers/csat_asset_mgmtController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using OwnYITCSAT.DataAccessLayer;
using OwnYITCSAT.Models;

namespace OwnYITCSAT.Controllers
{
    public class csat_asset_mgmtController : Controller
    {
        private int DBServer_Type = 0;
        private DatabaseHandler database = null;
        OwnYITConstant.DatabaseTypes dbtype;
        DBQueryHandler Objquery = new DBQueryHandler();
        OwnYITCommon Objcom = new OwnYITCommon();
        //string Auditdata = "";
        //string lastpolldata = "";
        //string PCdata = "";
        DataTable Dtsystemdrpdata = new DataTable();
        DataTable Dtsystempcdata = new DataTable();
        DataTable Dtsystemdata = new DataTable();
        DataTable DtAlerts = new DataTable();
        DataTable DtLastUser = new DataTable();
        DataTable DtDeviceStatus = new DataTable();
        DataTable DtOS = new DataTable();
        DataTable DtGroup = new DataTable();
        DataTable dttemp = new DataTable();
        DataTable HwData = new DataTable();
        DataTable DTfirewall = new DataTable();
        DataTable dtTable = new DataTable();
        string strmsg = "";
        DataTable DtShare = new DataTable();
        DataTable DtUser = new DataTable();
        DataTable dt = new DataTable();
        DataTable DtProcessor = new DataTable();
        DataTable DtDomain = new DataTable();
        DataTable DtDisk = new DataTable();
        DataTable DtRAM = new DataTable();
        DataTable dthw = new DataTable();
        DataTable dtsoft = new DataTable();
        int cnt = 0;
        Random generator = new Random();
        string groupid = Configuration.groupid;
        public IActionResult csat_asset_mgmt(int id)
        {
            //session time out start
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.password = HttpContext.Session.GetString("password");
            if (ViewBag.username == null && ViewBag.password == null)
            {
                return RedirectToAction("session_time_out", "csat_login");
            }
            else if (ViewBag.username == "" && ViewBag.password == "")
            {
                return RedirectToAction("csat_login", "csat_login");
            }
            else
                //session time out end
                // string abc = HttpContext.Session.GetString("user");
                HttpContext.Session.SetString("Flag", "");
            HttpContext.Session.SetString("DeviceID", "");
            try
            {
                if (OwnYITConstant.DT_ASSETMGMT_MENU == null)
                {
                    OwnYITConstant.DT_ASSETMGMT_MENU = Objquery.Get_SubMenu(id);
                }
                if (id.ToString() == null)
                    return RedirectToAction("csat_login", "csat_login");
                if (OwnYITConstant.DT_ASSETMGMT_MENU == null)
                    return RedirectToAction("csat_login", "csat_login");

                #region ViewBag Code
                //// Top 10 Asset ALert 
                //try
                //{
                //    ViewBag.alerts = Objcom.CreateTable(Objquery.Get_TopAlert());

                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Top 10 Asset ALert Table : " + ViewBag.alerts);
                //}
                //catch (Exception ex)
                //{
                //    ViewBag.alerts = "0";
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Top 10 Asset ALert Exception : " + ex.Message.ToString());
                //}

                //// OS Summary
                //try
                //{
                //    ViewBag.os = Objcom.CreateTable(Objquery.Get_OS());
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt OS Summary Table : " + ViewBag.os);
                //}
                //catch (Exception ex)
                //{
                //    ViewBag.os = "0";
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt OS Summary Exception : " + ex.Message.ToString());
                //}

                //// Processors Datails
                //try
                //{
                //    ViewBag.Processors = Objcom.CreateTable(Objquery.Get_Processor());
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Processors Datails Table : " + ViewBag.Processors);
                //}
                //catch (Exception ex)
                //{
                //    ViewBag.Processors = "0";
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Processors Datails Exception : " + ex.Message.ToString());
                //}

                //// User Summary
                //try
                //{
                //    ViewBag.UserSummary = Objcom.CreateTable(Objquery.Get_UserSummary());
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt User Summary Table : " + ViewBag.UserSummary);
                //}
                //catch (Exception ex)
                //{
                //    ViewBag.UserSummary = "0";
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt User Summary Exception : " + ex.Message.ToString());
                //}

                //// Domain Summary
                //try
                //{
                //    ViewBag.Domain = Objcom.CreateTable(Objquery.Get_Domain());
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Domain Summary Table : " + ViewBag.Domain);
                //}
                //catch (Exception ex)
                //{
                //    ViewBag.Domain = "0";
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Domain Summary Exception : " + ex.Message.ToString());
                //}

                //// Disk Utilization
                //try
                //{

                //    ViewBag.DiskUtilization = Objcom.CreateTable(Objquery.Get_HDDUsage());
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Disk Utilization Table : " + ViewBag.DiskUtilization);
                //}
                //catch (Exception ex)
                //{
                //    ViewBag.DiskUtilization = "0";
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Disk Utilization Exception : " + ex.Message.ToString());
                //}

                //// RAM Details
                //try
                //{

                //    ViewBag.RAM = Objcom.CreateTable(Objquery.Get_RAM_Details());
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt RAM Details Table : " + ViewBag.RAM);
                //}
                //catch (Exception ex)
                //{
                //    ViewBag.RAM = "0";
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt RAM Details Exception : " + ex.Message.ToString());
                //}


                //// Hardware Details
                //try
                //{

                //    ViewBag.Hardware = Objcom.CreateTable(Objquery.Get_Hardware_Details());
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Hardware Details Table : " + ViewBag.Hardware);
                //}
                //catch (Exception ex)
                //{
                //    ViewBag.Hardware = "0";
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Hardware Details Exception : " + ex.Message.ToString());
                //}

                //// Software Details
                //try
                //{
                //    DataTable dts = Objquery.Get_Software_Details();
                //    DTfirewall = Objquery.Get_Software_Details_Network_ON_OFF();

                //    string stroncnt = "";
                //    string stroffcnt = "";
                //    for (int i = 0; i < DTfirewall.Rows.Count; i++)
                //    {
                //        if ("ON" == DTfirewall.Rows[i]["TYPE"].ToString())
                //        {
                //            stroncnt = DTfirewall.Rows[i]["Counts"].ToString();
                //        }

                //        if ("OFF" == DTfirewall.Rows[i]["TYPE"].ToString())
                //        {
                //            stroffcnt = DTfirewall.Rows[i]["Counts"].ToString();
                //        }

                //    }
                //    string stronoff = stroncnt.ToString() + "/" + stroffcnt.ToString();

                //    //  ViewBag.firewallserviceonoff = stroncnt.ToString() + "/" + stroffcnt.ToString();
                //    DataRow dr;
                //    dr = dts.NewRow();
                //    dr["Software Details"] = "Firewall Service ON/OFF";
                //    dr["Counts"] =stronoff.ToString();
                //    dts.Rows.Add(dr);

                //    ViewBag.Software = Objcom.CreateTable(dts);
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Hardware Details Table : " + ViewBag.Software);

                //}
                //catch (Exception ex)
                //{
                //    ViewBag.Software = "0";
                //    Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt Hardware Details Exception : " + ex.Message.ToString());
                //}
                #endregion
            }
            catch (Exception ex)
            {
                Objcom.WriteLog("csat_asset_mgmtController", "csat_asset_mgmt  Exception : " + ex.Message.ToString());
            }
            return View();
        }

        public JsonResult GetAssetMgtTables()
        {

Views/csat_asset_mgmt/asset_assetmaster.cshtml
@{
    ViewData["Title"] = "Asset_assetmaster";
    Layout = "~/Views/Shared/ownyit_main_page.cshtml";
}

<div class="row">
    <div class="headerbar">
        <a href="#" style="padding-left:10px;">Asset Management</a>
    </div>
</div>


<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2">
        @{
            @Html.Partial("csat_asset_mgmt_menu");
        }

    </div>
    <div class="col-sm-10 col-md-10 col-lg-10">

        <ul class="breadcrumb">
            <li>
                @Html.ActionLink("Asset Management", "csat_asset_mgmt", "csat_asset_mgmt")
                <i class="icon-angle-right"></i>
            </li>

        </ul>
        <h1>Asset Master</h1>
    </div>
</div>

Views/csat_asset_mgmt/asset_maintanance.cshtml
@{
    ViewData["Title"] = "Asset_maintanance";
    Layout = "~/Views/Shared/ownyit_main_page.cshtml";
}


<div class="row">
    <div class="ibox float-e-margins ">
        <div class="ibox-content" style="padding:4px;">
            <ul class="breadcrumb" style="margin-bottom:0px;">
                <li>
                    @Html.ActionLink("Asset Management", "csat_asset_mgmt", "csat_asset_mgmt")
                    <i class="icon-angle-right"></i>
                </li>

            </ul>

        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2">
        @{
            @Html.Partial("csat_asset_mgmt_menu");
        }

    </div>
    <div class="col-sm-10 col-md-10 col-lg-10">

        <ul class="breadcrumb">
            <li>
                @Html.ActionLink("Asset Management", "csat_asset_mgmt", "csat_asset_mgmt")
                <i class="icon-angle-right"></i>
            </li>

        </ul>
        <h1>Maintanance</h1>
    </div>
</div>

Views/csat_asset_mgmt/asset_system_detail_menu.cshtml
<div class="category-tree mb30">   
    <div class="category-tree">
        <h2>Inventory</h2>
    </div>
    <ul class="subcategories">        
        <li class="89 div_none"><a data-toggle="modal" href="#" data-target="#hardware_popup" onclick='lodhardwaredetails()'>Hardware</a></li>
        <li class="90 div_none"><a data-toggle="modal" href="#" data-target="#software_popup" onclick='datasoftwarepopup()'>Software</a></li>
        <li class="91 div_none"><a data-toggle="modal" href="#" data-target="#share_popup" onclick='dataSharepopup()'>Share</a></li>
        <li class="92 div_none"><a data-toggle="modal" href="#" data-target="#user_popup" onclick='dataUserpopup()'>User</a></li>
        <li class="93 div_none"><a data-toggle="modal" href="#" data-target="#service_popup" onclick='dataServicepopup()'>Services</a></li>
        <li class="94 div_none"><a data-toggle="modal" href="#" data-target="#process_popup" onclick='dataProcesspopup()'>Processes</a></li>
        <li class="95 div_none"><a data-toggle="modal" href="#" data-target="#offline_systeminfo_popup" onclick='lodasystemdetails()'>Offline System Info</a></li>
    </ul>
    <div class="category-tree">
        <h2>Resource</h2>
    </div>
    <ul class="subcategories">
        <li class="96 div_none"><a data-toggle="modal" href="#" data-target="#system_utilization_popup" onclick='opensytemutilizationchart()'>System Utilization</a></li>
        <li class="97 div_none"><a data-toggle="modal" href="#" data-target="#system_network_popup" onclick='opensytemnetworktrafficchart()'>System Network Traffic</a></li>      
    </ul>
</div>

Views/csat_asset_mgmt/csat_asset_mgmt_asset_alertchart.cshtml
<div role="tabpanel" class="tab-pane fade active in" id="tab21" aria-labelledby="home-tab" style="width:100%;height:auto;">
    <div class="x_panel">
        <div class="x_content">
            <canvas id="csat_asset_mgmt_asset_alertchart" width="400" height="300"></canvas>
        </div>
    </div>
</div>

Views/csat_asset_mgmt/csat_asset_mgmt_device_status.cshtml
<div role="tabpanel" class="tab-pane fade active in" id="tab21" aria-labelledby="home-tab" style="width:100%;height:auto;">
    <div class="x_panel">
        <div class="x_content">
            <canvas id="csat_asset_mgmt_device_status" width="400" height="300"></canvas>           
        </div>
    </div>
</div>

Views/csat_asset_mgmt/csat_asset_mgmt_lastuserlogin.cshtml
<div role="tabpanel" class="tab-pane fade active in" id="tab21" aria-labelledby="home-tab" style="width:100%;height:auto;">
    <div class="x_panel">
        <div class="x_content">
            <canvas id="csat_asset_mgmt_lastuserlogin" width="400" height="300"></canvas>          
        </div>
    </div>
</div>

Views/csat_asset_mgmt/csat_asset_mgmt_menu.cshtml
<div class="category-tree mb30">   
    <ul class="subcategories">
        <li class="2  form_label div_none @(ViewContext.RouteData.Values["Action"].ToString() == "csat_asset_mgmt" ? "active" : "")">@Html.ActionLink("Asset Management", "csat_asset_mgmt", "csat_asset_mgmt")</li>
        <li class="52 div_none form_label @(ViewContext.RouteData.Values["Action"].ToString() == "asset_system_list" ? "active" : "")">@Html.ActionLink("System List", "asset_system_list", "csat_asset_mgmt")</li>
        <li class="53 div_none form_label @(ViewContext.RouteData.Values["Action"].ToString() == "asset_hardware_master" ? "active" : "")">@Html.ActionLink("Hardware Master", "asset_hardware_master", "csat_asset_mgmt")</li>
        <li class="54 div_none form_label @(ViewContext.RouteData.Values["Action"].ToString() == "asset_software_master" ? "active" : "")">@Html.ActionLink("Software Master", "asset_software_master", "csat_asset_mgmt")</li>
        <li class="55 div_none form_label @(ViewContext.RouteData.Values["Action"].ToString() == "asset_vendor_master" ? "active" : "")">@Html.ActionLink("Vendor Master", "asset_vendor_master", "csat_asset_mgmt")</li>        
    </ul>
</div>
<script>
    $(function () {
        var current_page_URL = location.href;
        $("a").each(function () {
            if ($(this).attr("href") !== "#") {
                var target_URL = $(this).prop("href");
                if (target_URL == current_page_URL) {
                    $('.category-tree').parents('li, ul').removeClass('active');
                    $(this).parent('li').addClass('active');
                    return false;
                }
            }
        });
    });
</script>