Controllers/csat_policy_mgmtController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OwnYITCSAT.DataAccessLayer;
using OwnYITCSAT.Models;

namespace OwnYITCSAT.Controllers
{
    public class csat_policy_mgmtController : Controller
    {
        private DatabaseHandler database = null;
        private int DBServer_Type = 0;
        OwnYITConstant.DatabaseTypes dbtype;
        string groupid = Configuration.groupid;
        DBQueryHandler Objquery = new DBQueryHandler();
        OwnYITCommon objcommon = new OwnYITCommon();
        DataTable dt = new DataTable();
        int querystatus = 0;
        int policyid = 0;
        int cnt = 0;
        string result = "";
        public IActionResult csat_policy_mgmt(int id)
        {
            //session time out start
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.password = HttpContext.Session.GetString("password");
            if (ViewBag.username == null && ViewBag.password == null)
            {
                return RedirectToAction("session_time_out", "csat_login");
            }
            else if (ViewBag.username == "" && ViewBag.password == "")
            {
                return RedirectToAction("csat_login", "csat_login");
            }
            else
                //session time out end
                try
                {
                    if (OwnYITConstant.DT_POLICY_MENU == null)
                    {
                        OwnYITConstant.DT_POLICY_MENU = Objquery.Get_SubMenu(id);
                    }
                    //  Session["Policyid"] = id;
                    if (id.ToString() == null)
                        return RedirectToAction("csat_login", "csat_login");
                    // Session["Policysubmenu"] = OwnYITConstant.DT_POLICY_MENU;
                    if (OwnYITConstant.DT_POLICY_MENU == null)
                        return RedirectToAction("csat_login", "csat_login");
                    return View();
                }
                catch (Exception ex)
                {
                    objcommon.WriteLog("csatpolicymgmtController", "csat_policy_mgmt Exception : " + ex.Message.ToString());
                }
            return View();
        }
        public IActionResult csat_policy_create()
        {
            //session time out start
            ViewBag.username = HttpContext.Session.GetString("username");
            ViewBag.password = HttpContext.Session.GetString("password");
            if (ViewBag.username == null && ViewBag.password == null)
            {
                return RedirectToAction("session_time_out", "csat_login");
            }
            else if (ViewBag.username == "" && ViewBag.password == "")
            {
                return RedirectToAction("csat_login", "csat_login");
            }
            else
                //session time out end

                return View();
        }
        //public JsonResult Get_Policy_data(int type)
        public JsonResult Get_Policy_data()
        {

            try
            {

                dt = Objquery.Get_Policy_Data("");
                //if (type == 4)
                //    dt = Objquery.Get_Policy_Data("type=4 and subtype=1");
                //else if (type == 42)
                //    dt = Objquery.Get_Policy_Data("type=4 and subtype=2");
                //else
                //    dt = Objquery.Get_Policy_Data("type=" + type + "");
            }
            catch (Exception ex)
            {
                objcommon.WriteLog("csatpolicymgmtController", "Get_Policy_data Exception : " + ex.Message.ToString());
            }
            var data = new { Policydata = dt };
            return Json(data);
        }
        public JsonResult Get_Policy_Save(string rulesid, string policyname, string description)
        {
            string result = "";
            try
            {
                if (policyname != "" && rulesid != "")
                    if (policyname != null && rulesid != null)
                    {
                        //cnt = Objquery.policy_master_count(policyname);
                        //if (cnt == 0)
                        //{
                        querystatus = Objquery.insert_policy_master(policyname, description);
                        policyid = Objquery.Get_Last_policy_Id();
                        querystatus = Objquery.insert_policy_linkage(policyid, rulesid.Substring(1));
                        if (querystatus == 0)
                            result = "Policy created failed.";
                        else
                            result = "Policy created successfully.";
                    }
                    else
                    {
                        result = "Please Enter Policy Details..";
                    }
            }
            catch (Exception ex)
            {
                objcommon.WriteLog("csatpolicymgmtController", "Get_Policy_Save Exception : " + ex.Message.ToString());
            }
            return Json(result);
        }

        //public JsonResult Get_Policy_Details_data(int type)
        public JsonResult Get_Policy_Details_data()
        {
            try
            {
                dt = Objquery.Get_Policy_Details_data();
                //if (type == 4)
                //    dt = Objquery.Get_Policy_Details_data("and r.type=4 and r.subtype=1");
                //else if (type == 42)
                //    dt = Objquery.Get_Policy_Details_data("and r.type=4 and  r.subtype=2");
                //else
                //    dt = Objquery.Get_Policy_Details_data("and r.type=" + type + "");
            }
            catch (Exception ex)
            {
                objcommon.WriteLog("csatpolicymgmtController", "Get_Policy_Details_data Exception : " + ex.Message.ToString());
            }
            var data = new { Policydetailsdata = dt };
            return Json(data);
        }
        public JsonResult GetPolicy(string name)
        {
            string type = "";
            if (name == "01")
            {
                dt = Objquery.Get_OUCount();
                type = "OU";
            }
            else if (name == "02")
            {
                dt = Objquery.Get_systemnameip();
                type = "System";
            }
            else
            {
                dt = Objquery.Get_Loginuser();
                type = "User";
            }
            var data = new { getapppolicydata = dt, gridtype = type };
            return Json(data);
        }
        public JsonResult GetPolicy_ipvalue(string name, string ip,string devicename)
        {
            string type = "";
            if (name == "01")
            {
                dt = Objquery.Get_OUCount();
                type = "OU";
            }
            else if (name == "02")
            {
                string strCond = "";
                if (devicename != null && devicename.Trim() != "")
                    strCond = " and device_name like '%"+devicename+"%'";
                dt = Objquery.Get_systemnameipsearch(ip, strCond);
                type = "System";
            }
            else
            {
                dt = Objquery.Get_Loginuser();
                type = "User";
            }
            var data = new { getapppolicydata = dt, gridtype = type };
            return Json(data);
        }
        public JsonResult Get_Policy(string policyid, string ostype)
        {
            string policyname = "";
            string osname = "";
            if (ostype == "0")
                osname = "Windows";
            else
                osname = "Linux";
            policyname = Objquery.Get_policyname(policyid);
            dt = Objquery.Get_systemnameip_apply(policyid, osname);
            var data = new { getapppolicydata = dt, policy_name = policyname };
            return Json(data);

            //string policyname = "";
            //string type = "";
            //policyname = Objquery.Get_policyname(policyid);
            //if (name == "01")
            //{
            //    dt = Objquery.Get_OUCount_apply();
            //    type = "OU";
            //}
            //else if (name == "02")
            //{
            //    dt = Objquery.Get_systemnameip_apply(policyid);
            //    type = "System";
            //}
            //else
            //{
            //    dt = Objquery.Get_Loginuser();
            //    type = "User";
            //}
            //var data = new { getapppolicydata = dt, gridtype = type, policy_name = policyname };
            //return Json(data);
        }
        public JsonResult Get_Policy_ip(string policyid, string ostype, string ip)
        {
            string policyname = "";
            string osname = "";
            if (ostype == "0")
                osname = "Windows";
            else
                osname = "Linux";
            policyname = Objquery.Get_policyname(policyid);
            if (ip == "null" || ip == "" || ip == null)
                dt = Objquery.Get_systemnameip_apply(policyid, osname);
            else
                dt = Objquery.Get_systemnameip_apply_ip(policyid, osname, ip);
            var data = new { getapppolicydata = dt, policy_name = policyname };
            return Json(data);
        }
        public JsonResult get_apply_policy_devices(string policy_id)
        {
            string policyname = "";
            DataTable dt = new DataTable();

            try
            {
                policyname = Objquery.Get_policyname(policy_id);
                dt = Objquery.Get_apply_policy_devices(policy_id);
            }
            catch (Exception ex)
            {
                objcommon.WriteLog("csatpolicymgmtController", "get_apply_policy_devices Exception : " + ex.Message.ToString());
            }
            var data = new { applypolicydevice = dt, policy_name = policyname };

Views/csat_policy_mgmt/csat_policy_mgmt.cshtml
@{
    ViewData["Title"] = "Policy Management";
    Layout = "~/Views/Shared/ownyit_main_page.cshtml";
}

@*<div class="row">
    <div class="headerbar">
        <a href="#" style="padding-left:10px;">Policy Enforcement</a>
    </div>
</div>*@
<div class="row">
    <div class="ibox float-e-margins">
        <div class="ibox-content" style="padding:4px;">
            <ul class="breadcrumb" style="margin-bottom:0px;">
                <li>
                    @Html.ActionLink("Policy Enforcement", "csat_policy_mgmt", "csat_policy_mgmt")
                    <i class="icon-angle-right"></i>
                </li>
            </ul>
        </div>
    </div>
</div>
    <!--Policy Management main content -->
    <body onload="Funcpolicycharts()">
        <div class="row">
            <!--Policy Management content-->
            <div class="col-sm-12 col-md-12 col-lg-12">               
                <!--Policy Management  chart  content-->

                <div class="row">

                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h6 class="pull-left">Branch/ Unit Wise Policy Deployed</h6>
                                <div class="col-xs-6 pull-right" style="margin-top:1px;margin-bottom:10px;">
                                    <select class="form-control col-sm-3 col-lg-3 col-md-3" name="Device" id="DrpOU" style="height: 24px;"></select>
                                </div>
                            </div>
                            <div class="ibox-content">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <canvas id='csat_policy_branch_unit' class="policy_chart"></canvas>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h6>System Wise Policy Infringe  </h6>
                                <div class="col-xs-2" style="float:right;top: -18px;right: 125px;">
                                    @*<select class="form-control col-sm-3 col-lg-3 col-md-3" name="Device" id="system" onchange="Funcpolicycharts(this.value)" style="height: 22px;width: 200px;">*@
                                    @*<select class="form-control col-sm-3 col-lg-3 col-md-3" name="Device" id="system" style="height: 22px;width: 200px;">
                        <option value="-1">Select System Name</option>
                        </select>*@
                                </div>
                            </div>
                            <div class="ibox-content">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <canvas id='csat_policy_system_deployed' class="policy_chart"></canvas>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h6>Total Available Policies</h6>
                            </div>
                            <div class="ibox-content">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <canvas id='csat_policy_total_available' class="policy_chart"></canvas>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>


                    <div class="col-sm-6 col-md-6 col-lg-6">
                        <div class="ibox float-e-margins">
                            <div class="ibox-title">
                                <h6>Deployed Policy</h6>
                            </div>
                            <div class="ibox-content">
                                <div class="x_panel">
                                    <div class="x_content">
                                        <canvas id='csat_policy_deployed' class="policy_chart"></canvas>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <!--Policy Management  chart end content-->
                <!--Policy Management  table  content-->

                <div class="row">

                </div>


                <!--Policy Management  table  content end-->
                <div class="space_bottom">&nbsp;</div>
            </div> <!-- Policy Management content end-->
        </div>  <!-- Policy Management main content end*-->

    </body>
    <!--Policy Management  -->
    <script>
    $.get('@Url.Content("~/csat_report/GetOU/")', null, DataBind)
    function DataBind(data) {
	 //debugger;
        var url = '@Url.Content("~/csat_report/GetOU/")';
        $.ajax({
            type: "POST",
            url: url,
            success: function (data) {
	         var SetData = $('#DrpOU');
			  jQuery('#DrpOU').html('');
			  var oudata = "<option value='-1'>Select Branch/ Unit</option>";
                //var oudata = "";
                for (var i = 0; i < data.ou.length; i++) {
                        oudata += "<option value='" + data.ou[0].ouid + "'>" + data.ou[i].ouname + "</option>";
                }
                SetData.append(oudata);
            }
        });
	}


    </script>
    <script>

    var ouid;
    $("#DrpOU").change(function () {
       // debugger;
        ouid = this.value;
        var url = '@Url.Content("~/csat_policy_mgmt/GetPolicyCharts?device=")' + ouid;
            $.ajax({
                type: "POST",
                url: url,
                success: function (data) {
                    group_barchart('csat_policy_branch_unit', data.chartstrdepoupolicy, '#003399', '#a02c5a', 'Defult Policy', 'User Define Policy');
                }
            });
        });

          function Funcpolicycharts() {
           // debugger;
              $("#overlay").show();
              $("#overlay").fadeIn(300);　
            var url = '@Url.Content("~/csat_policy_mgmt/GetPolicyCharts?device=")' + "";
            $.ajax({
                type: "POST",
                url: url,
                success: function (data) {
                    //debugger;
                    var SetDatadevice = $('#system');
                    jQuery('#system').html('');
                    var devicedata = "<option value='-1'>Select System Name</option>";
                    for (var i = 0; i < data.sysip.length; i++) {
                        devicedata += "<option value='" + data.sysip[i].device_id + "'>" + data.sysip[i].device_name + "</option>";
                    }
                    SetDatadevice.append(devicedata);
                    group_barchart('csat_policy_deployed', data.chartstrdeppolicy, '#C00000', '#2cc2c2 ', 'Defult Policy','User Define Policy');
                    group_barchart('csat_policy_total_available', data.chartstravlpolicy, '#A055BC ', '#FFCC00 ', 'Defult Policy', 'User Define Policy');
                    group_barchart('csat_policy_system_deployed', data.chartstrdepsyspolicy, '#009900', '#FF9900', 'Available Policies','Infringe Policies');
                    group_barchart('csat_policy_branch_unit', data.chartstrdepoupolicy, '#003399', '#a02c5a', 'Defult Policy', 'User Define Policy');

                }

            }).done(function () {
                setTimeout(function () {
                    $("#overlay").fadeOut(300);
                }, 500);
            });
        }
    </script>
    <!--Policy Management  End -->